// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.user_id", "3a954982-5057-4d77-befe-8104c32244c9");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.allowUpdatesForUnelevatedInstallations", true);
user_pref("app.update.background.lastInstalledTaskVersion", 4);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.langpack.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1742229243);
user_pref("app.update.lastUpdateTime.background-update-timer", 1742229243);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1742229243);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1742229243);
user_pref("app.update.lastUpdateTime.region-update-timer", 1742229243);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1754117538);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1742229243);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1741366365);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1742229243);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.newtabpage.activity-stream.asrouter.debugLogLevel", "error");
user_pref("browser.newtabpage.activity-stream.impressionId", "{da53ddff-80f8-48fd-8ed7-a2977d5a245f}");
user_pref("browser.region.update.updated", 1741441938);
user_pref("browser.search.region", "PT");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "4d93c39b-c908-4307-a3cb-fe02a459dff6");
user_pref("datareporting.dau.cachedUsageProfileID", "325caff6-8c46-4286-a2ca-b4307f47a322");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1741366334916");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("messaging-system.log", "error");
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 2);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "8123179e-f217-47ac-816b-4f374bb658c4");
user_pref("services.settings.loglevel", "error");
user_pref("toolkit.backgroundtasks.loglevel", "error");
user_pref("toolkit.profiles.storeID", "97866722");
user_pref("toolkit.startup.last_success", 1754117536);
user_pref("toolkit.telemetry.cachedClientID", "21346f6b-dc28-43f3-854f-a4e352fefa8c");
user_pref("toolkit.telemetry.cachedProfileGroupID", "c17dd701-2824-4de7-82e4-b75651ab4878");
