// Word Quest - Word Database
// Contains valid 5-letter words for the game

// Daily words pool - these are the target words players need to guess
const DAILY_WORDS = [
    'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER', 'AGAIN',
    'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE',
    'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'AMONG', 'ANGER', 'ANGLE', 'ANGRY', 'APART', 'APPLE',
    'APPLY', 'ARENA', 'ARGUE', 'ARISE', 'ARRAY', 'ASIDE', 'ASSET', 'AVOID', 'AWAKE', 'AWARD',
    'AWARE', 'BADLY', 'BAKER', 'BASES', 'BASIC', 'BEACH', 'BEGAN', 'BEGIN', 'BEING', 'BELOW',
    'BENCH', 'BILLY', 'BIRTH', 'BLACK', 'BLAME', 'BLANK', 'BLAST', 'BLIND', 'BLOCK', 'BLOOD',
    'BOARD', 'BOOST', 'BOOTH', 'BOUND', 'BRAIN', 'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK',
    'BREED', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROWN', 'BUILD', 'BUILT', 'BUYER', 'CABLE',
    'CALIF', 'CARRY', 'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHAOS', 'CHARM', 'CHART', 'CHASE',
    'CHEAP', 'CHECK', 'CHEST', 'CHIEF', 'CHILD', 'CHINA', 'CHOSE', 'CIVIL', 'CLAIM', 'CLASS',
    'CLEAN', 'CLEAR', 'CLICK', 'CLIMB', 'CLOCK', 'CLOSE', 'CLOUD', 'COACH', 'COAST', 'COULD',
    'COUNT', 'COURT', 'COVER', 'CRAFT', 'CRASH', 'CRAZY', 'CREAM', 'CRIME', 'CROSS', 'CROWD',
    'CROWN', 'CRUDE', 'CURVE', 'CYCLE', 'DAILY', 'DANCE', 'DATED', 'DEALT', 'DEATH', 'DEBUT',
    'DELAY', 'DEPTH', 'DOING', 'DOUBT', 'DOZEN', 'DRAFT', 'DRAMA', 'DRANK', 'DRAWN', 'DREAM',
    'DRESS', 'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DYING', 'EAGER', 'EARLY', 'EARTH', 'EIGHT',
    'ELITE', 'EMPTY', 'ENEMY', 'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'ERROR', 'EVENT', 'EVERY',
    'EXACT', 'EXIST', 'EXTRA', 'FAITH', 'FALSE', 'FAULT', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY',
    'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLASH', 'FLEET', 'FLOOR', 'FLUID', 'FOCUS', 'FORCE',
    'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FRUIT',
    'FULLY', 'FUNNY', 'GIANT', 'GIVEN', 'GLASS', 'GLOBE', 'GOING', 'GRACE', 'GRADE', 'GRAND',
    'GRANT', 'GRASS', 'GRAVE', 'GREAT', 'GREEN', 'GROSS', 'GROUP', 'GROWN', 'GUARD', 'GUESS',
    'GUEST', 'GUIDE', 'HAPPY', 'HARRY', 'HEART', 'HEAVY', 'HENCE', 'HENRY', 'HORSE', 'HOTEL',
    'HOUSE', 'HUMAN', 'IDEAL', 'IMAGE', 'INDEX', 'INNER', 'INPUT', 'ISSUE', 'JAPAN', 'JIMMY',
    'JOINT', 'JONES', 'JUDGE', 'KNOWN', 'LABEL', 'LARGE', 'LASER', 'LATER', 'LAUGH', 'LAYER',
    'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEGAL', 'LEVEL', 'LEWIS', 'LIGHT', 'LIMIT', 'LINKS',
    'LIVES', 'LOCAL', 'LOOSE', 'LOWER', 'LUCKY', 'LUNCH', 'LYING', 'MAGIC', 'MAJOR', 'MAKER',
    'MARCH', 'MARIA', 'MATCH', 'MAYBE', 'MAYOR', 'MEANT', 'MEDIA', 'METAL', 'MIGHT', 'MINOR',
    'MINUS', 'MIXED', 'MODEL', 'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH',
    'MOVED', 'MOVIE', 'MUSIC', 'NEEDS', 'NEVER', 'NEWLY', 'NIGHT', 'NOISE', 'NORTH', 'NOTED',
    'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'ORDER', 'OTHER', 'OUGHT', 'PAINT',
    'PANEL', 'PAPER', 'PARTY', 'PEACE', 'PETER', 'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PIECE',
    'PILOT', 'PITCH', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'POINT', 'POUND', 'POWER',
    'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRIZE', 'PROOF', 'PROUD', 'PROVE',
    'QUEEN', 'QUICK', 'QUIET', 'QUITE', 'RADIO', 'RAISE', 'RANGE', 'RAPID', 'RATIO', 'REACH',
    'READY', 'REALM', 'REBEL', 'REFER', 'RELAX', 'REPAY', 'REPLY', 'RIGHT', 'RIGID', 'RIVAL',
    'RIVER', 'ROBIN', 'ROGER', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RURAL', 'SCALE',
    'SCENE', 'SCOPE', 'SCORE', 'SENSE', 'SERVE', 'SETUP', 'SEVEN', 'SHALL', 'SHAPE', 'SHARE',
    'SHARP', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHIRT', 'SHOCK', 'SHOOT', 'SHORT',
    'SHOWN', 'SIGHT', 'SILLY', 'SINCE', 'SIXTH', 'SIXTY', 'SIZED', 'SKILL', 'SLEEP', 'SLIDE',
    'SMALL', 'SMART', 'SMILE', 'SMITH', 'SMOKE', 'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH',
    'SPACE', 'SPARE', 'SPEAK', 'SPEED', 'SPEND', 'SPENT', 'SPLIT', 'SPOKE', 'SPORT', 'STAFF',
    'STAGE', 'STAKE', 'STAND', 'START', 'STATE', 'STEAM', 'STEEL', 'STEEP', 'STEER', 'STICK',
    'STILL', 'STOCK', 'STONE', 'STOOD', 'STORE', 'STORM', 'STORY', 'STRIP', 'STUCK', 'STUDY',
    'STUFF', 'STYLE', 'SUGAR', 'SUITE', 'SUPER', 'SWEET', 'TABLE', 'TAKEN', 'TASTE', 'TAXES',
    'TEACH', 'TEAMS', 'TEETH', 'TERRY', 'TEXAS', 'THANK', 'THEFT', 'THEIR', 'THEME', 'THERE',
    'THESE', 'THICK', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'THREW', 'THROW', 'THUMB',
    'TIGHT', 'TIRED', 'TITLE', 'TODAY', 'TOPIC', 'TOTAL', 'TOUCH', 'TOUGH', 'TOWER', 'TRACK',
    'TRADE', 'TRAIN', 'TREAT', 'TREND', 'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TRUCK',
    'TRULY', 'TRUNK', 'TRUST', 'TRUTH', 'TWICE', 'TWIST', 'TYLER', 'UNDER', 'UNDUE', 'UNION',
    'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN', 'USAGE', 'USUAL', 'VALID', 'VALUE', 'VIDEO',
    'VIRUS', 'VISIT', 'VITAL', 'VOCAL', 'VOICE', 'WASTE', 'WATCH', 'WATER', 'WHEEL', 'WHERE',
    'WHICH', 'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WOMAN', 'WOMEN', 'WORLD', 'WORRY', 'WORSE',
    'WORST', 'WORTH', 'WOULD', 'WRITE', 'WRONG', 'WROTE', 'YOUNG', 'YOUTH'
];

// Valid guess words - includes all daily words plus additional common 5-letter words
const VALID_WORDS = [
    ...DAILY_WORDS,
    'AAHED', 'AALII', 'AARGH', 'AARTI', 'ABACA', 'ABACI', 'ABACK', 'ABACS', 'ABAFT', 'ABAKA',
    'ABAMP', 'ABAND', 'ABASE', 'ABASH', 'ABASK', 'ABATE', 'ABAYA', 'ABBAS', 'ABBED', 'ABBES',
    'ABBEY', 'ABBOT', 'ABCEE', 'ABEAM', 'ABEAR', 'ABELE', 'ABERS', 'ABETS', 'ABHOR', 'ABIDE',
    'ABLED', 'ABLER', 'ABLES', 'ABLET', 'ABLOW', 'ABMHO', 'ABODE', 'ABOHM', 'ABOIL', 'ABOMA',
    'ABOON', 'ABORD', 'ABORE', 'ABORT', 'ABOS', 'ABOUL', 'ABRAM', 'ABRAY', 'ABRED', 'ABRI',
    'ABRIM', 'ABRIN', 'ABRIS', 'ABSEY', 'ABSIT', 'ABUNA', 'ABUNE', 'ABURS', 'ABUSH', 'ABUTS',
    'ABUZZ', 'ABYES', 'ABYSM', 'ABYSS', 'ACAIS', 'ACARI', 'ACCAS', 'ACCOY', 'ACERB', 'ACERS',
    'ACETA', 'ACHAR', 'ACHED', 'ACHES', 'ACHOO', 'ACIDS', 'ACIDY', 'ACING', 'ACINI', 'ACKEE',
    'ACKER', 'ACMES', 'ACNED', 'ACNES', 'ACOCK', 'ACOLD', 'ACORN', 'ACRED', 'ACRES', 'ACRID',
    'ACROS', 'ACTED', 'ACTIN', 'ACTON', 'ACTS', 'ACUFF', 'ACULE', 'ACUMEN', 'ACUTE', 'ACYLS'
];

// Word hints - definitions for some common words
const WORD_HINTS = {
    'ABOUT': 'Concerning or regarding',
    'ABOVE': 'Higher than or over',
    'ACTOR': 'Person who performs in plays or movies',
    'AFTER': 'Following in time',
    'AGAIN': 'Once more',
    'AGENT': 'Person who acts on behalf of another',
    'AGREE': 'To have the same opinion',
    'ALARM': 'Warning signal',
    'ALBUM': 'Collection of photos or music',
    'ALERT': 'Watchful and ready',
    'ALIEN': 'From another world',
    'ALIVE': 'Living, not dead',
    'ALLOW': 'To permit',
    'ALONE': 'By oneself',
    'ALONG': 'In company with',
    'ANGER': 'Strong feeling of displeasure',
    'ANGLE': 'Space between two intersecting lines',
    'ANGRY': 'Feeling or showing anger',
    'APPLE': 'Red or green fruit',
    'APPLY': 'To put to use',
    'ARGUE': 'To give reasons for or against',
    'ARISE': 'To get up or come up',
    'ARRAY': 'Orderly arrangement',
    'ASIDE': 'To one side',
    'ASSET': 'Valuable thing or person',
    'AVOID': 'To keep away from',
    'AWAKE': 'Not sleeping',
    'AWARD': 'Prize or honor given',
    'AWARE': 'Having knowledge of',
    'BADLY': 'In a bad manner',
    'BAKER': 'Person who bakes bread',
    'BASIC': 'Fundamental or essential',
    'BEACH': 'Sandy shore by the sea',
    'BEGIN': 'To start',
    'BEING': 'Existence or creature',
    'BELOW': 'Under or beneath',
    'BENCH': 'Long seat',
    'BIRTH': 'Act of being born',
    'BLACK': 'Darkest color',
    'BLAME': 'To hold responsible',
    'BLANK': 'Empty or without marks',
    'BLAST': 'Strong gust of air',
    'BLIND': 'Unable to see',
    'BLOCK': 'Solid piece of material',
    'BLOOD': 'Red liquid in the body',
    'BOARD': 'Flat piece of wood',
    'BOOST': 'To help or encourage',
    'BOOTH': 'Small enclosed area',
    'BOUND': 'Tied up or certain to',
    'BRAIN': 'Organ of thought',
    'BRAND': 'Make or trademark',
    'BRASS': 'Yellow metal alloy',
    'BRAVE': 'Showing courage',
    'BREAD': 'Baked food made from flour',
    'BREAK': 'To separate into pieces',
    'BREED': 'To produce offspring',
    'BRIEF': 'Short in time or duration',
    'BRING': 'To carry or take along',
    'BROAD': 'Wide',
    'BROKE': 'Having no money',
    'BROWN': 'Color of earth or wood',
    'BUILD': 'To construct',
    'BUILT': 'Past tense of build',
    'BUYER': 'Person who purchases',
    'CABLE': 'Thick rope or wire',
    'CARRY': 'To transport',
    'CATCH': 'To grab or capture',
    'CAUSE': 'Reason for something',
    'CHAIN': 'Series of connected links',
    'CHAIR': 'Seat with a back',
    'CHAOS': 'Complete disorder',
    'CHARM': 'Attractive quality',
    'CHART': 'Map or diagram',
    'CHASE': 'To pursue',
    'CHEAP': 'Low in price',
    'CHECK': 'To examine or verify',
    'CHEST': 'Upper front of the body',
    'CHIEF': 'Leader or head',
    'CHILD': 'Young human being',
    'CHINA': 'Fine porcelain',
    'CHOSE': 'Past tense of choose',
    'CIVIL': 'Relating to citizens',
    'CLAIM': 'To assert ownership',
    'CLASS': 'Group or category',
    'CLEAN': 'Free from dirt',
    'CLEAR': 'Easy to see through',
    'CLICK': 'Short sharp sound',
    'CLIMB': 'To go up',
    'CLOCK': 'Device that shows time',
    'CLOSE': 'Near or to shut',
    'CLOUD': 'Mass of water vapor',
    'COACH': 'Trainer or instructor',
    'COAST': 'Land near the sea',
    'COULD': 'Past tense of can',
    'COUNT': 'To number',
    'COURT': 'Place where justice is administered',
    'COVER': 'To place over',
    'CRAFT': 'Skill or small boat',
    'CRASH': 'Violent collision',
    'CRAZY': 'Mentally unbalanced',
    'CREAM': 'Thick part of milk',
    'CRIME': 'Illegal act',
    'CROSS': 'To go across',
    'CROWD': 'Large group of people',
    'CROWN': 'Royal headpiece',
    'CRUDE': 'In natural state',
    'CURVE': 'Bent line',
    'CYCLE': 'Series of events',
    'DAILY': 'Every day',
    'DANCE': 'Rhythmic movement',
    'DATED': 'Showing the date',
    'DEALT': 'Past tense of deal',
    'DEATH': 'End of life',
    'DEBUT': 'First appearance',
    'DELAY': 'To postpone',
    'DEPTH': 'Distance downward',
    'DOING': 'Performing an action',
    'DOUBT': 'Uncertainty',
    'DOZEN': 'Twelve',
    'DRAFT': 'Rough version',
    'DRAMA': 'Play or exciting situation',
    'DRANK': 'Past tense of drink',
    'DRAWN': 'Past participle of draw',
    'DREAM': 'Images during sleep',
    'DRESS': 'Garment or to clothe',
    'DRILL': 'Tool for making holes',
    'DRINK': 'To swallow liquid',
    'DRIVE': 'To operate a vehicle',
    'DROVE': 'Past tense of drive',
    'DYING': 'Near death',
    'EAGER': 'Enthusiastic',
    'EARLY': 'Before the usual time',
    'EARTH': 'Our planet',
    'EIGHT': 'Number after seven',
    'ELITE': 'Best or most skilled',
    'EMPTY': 'Containing nothing',
    'ENEMY': 'Opponent or foe',
    'ENJOY': 'To take pleasure in',
    'ENTER': 'To go into',
    'ENTRY': 'Act of entering',
    'EQUAL': 'The same in quantity',
    'ERROR': 'Mistake',
    'EVENT': 'Something that happens',
    'EVERY': 'Each one',
    'EXACT': 'Precise',
    'EXIST': 'To be real',
    'EXTRA': 'Additional',
    'FAITH': 'Trust or belief',
    'FALSE': 'Not true',
    'FAULT': 'Defect or blame',
    'FIBER': 'Thread-like structure',
    'FIELD': 'Open area of land',
    'FIFTH': 'Number five in order',
    'FIFTY': 'Number 50',
    'FIGHT': 'To battle',
    'FINAL': 'Last',
    'FIRST': 'Before all others',
    'FIXED': 'Repaired or stationary',
    'FLASH': 'Brief burst of light',
    'FLEET': 'Group of ships',
    'FLOOR': 'Bottom surface of a room',
    'FLUID': 'Liquid substance',
    'FOCUS': 'To concentrate',
    'FORCE': 'Strength or power',
    'FORTH': 'Forward',
    'FORTY': 'Number 40',
    'FORUM': 'Place for discussion',
    'FOUND': 'Past tense of find',
    'FRAME': 'Border or structure',
    'FRANK': 'Honest and direct',
    'FRAUD': 'Deception for gain',
    'FRESH': 'New or not stale',
    'FRONT': 'Forward part',
    'FRUIT': 'Sweet plant product',
    'FULLY': 'Completely',
    'FUNNY': 'Amusing',
    'GIANT': 'Very large',
    'GIVEN': 'Past participle of give',
    'GLASS': 'Transparent material',
    'GLOBE': 'Sphere or Earth',
    'GOING': 'Moving or traveling',
    'GRACE': 'Elegance or divine favor',
    'GRADE': 'Level or mark',
    'GRAND': 'Impressive or large',
    'GRANT': 'To give or allow',
    'GRASS': 'Green plant covering',
    'GRAVE': 'Serious or burial place',
    'GREAT': 'Large or excellent',
    'GREEN': 'Color of grass',
    'GROSS': 'Total or disgusting',
    'GROUP': 'Collection of people',
    'GROWN': 'Past participle of grow',
    'GUARD': 'To protect',
    'GUESS': 'To estimate',
    'GUEST': 'Visitor',
    'GUIDE': 'To lead or direct',
    'HAPPY': 'Feeling joy',
    'HEART': 'Organ that pumps blood',
    'HEAVY': 'Having great weight',
    'HENCE': 'Therefore',
    'HORSE': 'Four-legged animal',
    'HOTEL': 'Place to stay',
    'HOUSE': 'Building to live in',
    'HUMAN': 'Person',
    'IDEAL': 'Perfect',
    'IMAGE': 'Picture or representation',
    'INDEX': 'List or pointer',
    'INNER': 'Inside',
    'INPUT': 'Information put in',
    'ISSUE': 'Problem or topic',
    'JAPAN': 'Asian country',
    'JOINT': 'Connection or shared',
    'JUDGE': 'Person who decides',
    'KNOWN': 'Familiar or recognized',
    'LABEL': 'Tag or name',
    'LARGE': 'Big in size',
    'LASER': 'Focused light beam',
    'LATER': 'At a future time',
    'LAUGH': 'To express amusement',
    'LAYER': 'Sheet or level',
    'LEARN': 'To gain knowledge',
    'LEASE': 'To rent',
    'LEAST': 'Smallest amount',
    'LEAVE': 'To go away',
    'LEGAL': 'According to law',
    'LEVEL': 'Height or degree',
    'LIGHT': 'Illumination',
    'LIMIT': 'Boundary or restriction',
    'LINKS': 'Connections',
    'LIVES': 'Plural of life',
    'LOCAL': 'Nearby or regional',
    'LOOSE': 'Not tight',
    'LOWER': 'Below or to reduce',
    'LUCKY': 'Fortunate',
    'LUNCH': 'Midday meal',
    'LYING': 'Not telling truth',
    'MAGIC': 'Supernatural power',
    'MAJOR': 'Important or large',
    'MAKER': 'One who creates',
    'MARCH': 'To walk in step',
    'MATCH': 'To pair or game',
    'MAYBE': 'Perhaps',
    'MAYOR': 'City leader',
    'MEANT': 'Past tense of mean',
    'MEDIA': 'Communication channels',
    'METAL': 'Hard shiny material',
    'MIGHT': 'Strength or possibility',
    'MINOR': 'Small or young person',
    'MINUS': 'Less or negative',
    'MIXED': 'Combined',
    'MODEL': 'Example or representation',
    'MONEY': 'Currency',
    'MONTH': 'Period of about 30 days',
    'MORAL': 'Right and wrong',
    'MOTOR': 'Engine',
    'MOUNT': 'To climb or mountain',
    'MOUSE': 'Small rodent',
    'MOUTH': 'Opening for eating',
    'MOVED': 'Past tense of move',
    'MOVIE': 'Film',
    'MUSIC': 'Organized sound',
    'NEEDS': 'Requirements',
    'NEVER': 'Not ever',
    'NEWLY': 'Recently',
    'NIGHT': 'Dark time',
    'NOISE': 'Unwanted sound',
    'NORTH': 'Direction opposite south',
    'NOTED': 'Famous or observed',
    'NOVEL': 'Book or new',
    'NURSE': 'Medical caregiver',
    'OCCUR': 'To happen',
    'OCEAN': 'Large body of water',
    'OFFER': 'To present for acceptance',
    'OFTEN': 'Frequently',
    'ORDER': 'Arrangement or command',
    'OTHER': 'Different',
    'OUGHT': 'Should',
    'PAINT': 'Colored liquid coating',
    'PANEL': 'Flat surface',
    'PAPER': 'Thin sheet material',
    'PARTY': 'Social gathering',
    'PEACE': 'Absence of war',
    'PHASE': 'Stage or period',
    'PHONE': 'Communication device',
    'PHOTO': 'Picture',
    'PIANO': 'Musical instrument',
    'PIECE': 'Part or portion',
    'PILOT': 'Person who flies aircraft',
    'PITCH': 'To throw or musical tone',
    'PLACE': 'Location',
    'PLAIN': 'Simple or flat area',
    'PLANE': 'Aircraft or flat surface',
    'PLANT': 'Living organism or factory',
    'PLATE': 'Flat dish',
    'POINT': 'Sharp end or location',
    'POUND': 'Unit of weight',
    'POWER': 'Strength or energy',
    'PRESS': 'To push or media',
    'PRICE': 'Cost',
    'PRIDE': 'Self-respect',
    'PRIME': 'First or best',
    'PRINT': 'To produce text',
    'PRIOR': 'Before',
    'PRIZE': 'Award',
    'PROOF': 'Evidence',
    'PROUD': 'Feeling pride',
    'PROVE': 'To demonstrate',
    'QUEEN': 'Female ruler',
    'QUICK': 'Fast',
    'QUIET': 'Silent',
    'QUITE': 'Rather or completely',
    'RADIO': 'Broadcasting device',
    'RAISE': 'To lift up',
    'RANGE': 'Extent or series',
    'RAPID': 'Very fast',
    'RATIO': 'Proportion',
    'REACH': 'To extend to',
    'READY': 'Prepared',
    'REALM': 'Kingdom or domain',
    'REBEL': 'To resist authority',
    'REFER': 'To mention',
    'RELAX': 'To rest',
    'REPAY': 'To pay back',
    'REPLY': 'To answer',
    'RIGHT': 'Correct or direction',
    'RIGID': 'Stiff',
    'RIVAL': 'Competitor',
    'RIVER': 'Flowing water',
    'ROUGH': 'Not smooth',
    'ROUND': 'Circular',
    'ROUTE': 'Path or way',
    'ROYAL': 'Of a king or queen',
    'RURAL': 'Countryside',
    'SCALE': 'Size or to climb',
    'SCENE': 'View or setting',
    'SCOPE': 'Range or extent',
    'SCORE': 'Points or twenty',
    'SENSE': 'Feeling or meaning',
    'SERVE': 'To help or provide',
    'SETUP': 'Arrangement',
    'SEVEN': 'Number after six',
    'SHALL': 'Will or must',
    'SHAPE': 'Form',
    'SHARE': 'To divide',
    'SHARP': 'Having a fine edge',
    'SHEET': 'Thin layer',
    'SHELF': 'Horizontal surface',
    'SHELL': 'Hard outer covering',
    'SHIFT': 'To move or change',
    'SHINE': 'To give off light',
    'SHIRT': 'Upper body garment',
    'SHOCK': 'Sudden surprise',
    'SHOOT': 'To fire or grow',
    'SHORT': 'Not long',
    'SHOWN': 'Past participle of show',
    'SIGHT': 'Vision',
    'SILLY': 'Foolish',
    'SINCE': 'From then until now',
    'SIXTH': 'Number six in order',
    'SIXTY': 'Number 60',
    'SIZED': 'Having a particular size',
    'SKILL': 'Ability',
    'SLEEP': 'Rest state',
    'SLIDE': 'To move smoothly',
    'SMALL': 'Little',
    'SMART': 'Intelligent',
    'SMILE': 'Happy expression',
    'SMOKE': 'Visible vapor',
    'SOLID': 'Firm or reliable',
    'SOLVE': 'To find answer',
    'SORRY': 'Feeling regret',
    'SOUND': 'Noise or healthy',
    'SOUTH': 'Direction opposite north',
    'SPACE': 'Empty area',
    'SPARE': 'Extra or to save',
    'SPEAK': 'To talk',
    'SPEED': 'Rate of movement',
    'SPEND': 'To use money',
    'SPENT': 'Past tense of spend',
    'SPLIT': 'To divide',
    'SPOKE': 'Past tense of speak',
    'SPORT': 'Physical activity',
    'STAFF': 'Workers or stick',
    'STAGE': 'Platform or phase',
    'STAKE': 'Post or risk',
    'STAND': 'To be upright',
    'START': 'To begin',
    'STATE': 'Condition or region',
    'STEAM': 'Water vapor',
    'STEEL': 'Strong metal',
    'STEEP': 'Having sharp slope',
    'STEER': 'To guide',
    'STICK': 'Thin piece of wood',
    'STILL': 'Motionless or yet',
    'STOCK': 'Supply or shares',
    'STONE': 'Hard mineral',
    'STOOD': 'Past tense of stand',
    'STORE': 'Shop or to keep',
    'STORM': 'Violent weather',
    'STORY': 'Tale or floor',
    'STRIP': 'Narrow piece',
    'STUCK': 'Past tense of stick',
    'STUDY': 'To learn',
    'STUFF': 'Things or material',
    'STYLE': 'Fashion or manner',
    'SUGAR': 'Sweet substance',
    'SUITE': 'Set of rooms',
    'SUPER': 'Excellent',
    'SWEET': 'Having sugar taste',
    'TABLE': 'Furniture with flat top',
    'TAKEN': 'Past participle of take',
    'TASTE': 'Flavor sensation',
    'TAXES': 'Government charges',
    'TEACH': 'To instruct',
    'TEAMS': 'Groups working together',
    'TEETH': 'Plural of tooth',
    'THANK': 'To express gratitude',
    'THEFT': 'Act of stealing',
    'THEIR': 'Belonging to them',
    'THEME': 'Main subject',
    'THERE': 'In that place',
    'THESE': 'Plural of this',
    'THICK': 'Not thin',
    'THING': 'Object or matter',
    'THINK': 'To use mind',
    'THIRD': 'Number three in order',
    'THOSE': 'Plural of that',
    'THREE': 'Number after two',
    'THREW': 'Past tense of throw',
    'THROW': 'To hurl',
    'THUMB': 'Short thick finger',
    'TIGHT': 'Firmly fixed',
    'TIRED': 'Needing rest',
    'TITLE': 'Name or rank',
    'TODAY': 'This day',
    'TOPIC': 'Subject',
    'TOTAL': 'Complete amount',
    'TOUCH': 'To feel with fingers',
    'TOUGH': 'Strong or difficult',
    'TOWER': 'Tall structure',
    'TRACK': 'Path or to follow',
    'TRADE': 'To exchange',
    'TRAIN': 'Railway vehicle',
    'TREAT': 'To handle or gift',
    'TREND': 'General direction',
    'TRIAL': 'Test or court case',
    'TRIBE': 'Social group',
    'TRICK': 'Clever act',
    'TRIED': 'Past tense of try',
    'TRIES': 'Attempts',
    'TRUCK': 'Large vehicle',
    'TRULY': 'Really',
    'TRUNK': 'Tree stem or box',
    'TRUST': 'Confidence',
    'TRUTH': 'Fact or reality',
    'TWICE': 'Two times',
    'TWIST': 'To turn',
    'UNDER': 'Below',
    'UNDUE': 'Excessive',
    'UNION': 'Joining together',
    'UNITY': 'Being united',
    'UNTIL': 'Up to the time',
    'UPPER': 'Higher',
    'UPSET': 'Disturbed',
    'URBAN': 'Of a city',
    'USAGE': 'Way of using',
    'USUAL': 'Normal',
    'VALID': 'Acceptable',
    'VALUE': 'Worth',
    'VIDEO': 'Moving pictures',
    'VIRUS': 'Infectious agent',
    'VISIT': 'To go see',
    'VITAL': 'Essential',
    'VOCAL': 'Relating to voice',
    'VOICE': 'Sound from mouth',
    'WASTE': 'To use carelessly',
    'WATCH': 'To observe',
    'WATER': 'Clear liquid',
    'WHEEL': 'Circular object',
    'WHERE': 'In what place',
    'WHICH': 'What one',
    'WHILE': 'During the time',
    'WHITE': 'Color of snow',
    'WHOLE': 'Complete',
    'WHOSE': 'Belonging to whom',
    'WOMAN': 'Adult female',
    'WOMEN': 'Plural of woman',
    'WORLD': 'Earth or universe',
    'WORRY': 'To be anxious',
    'WORSE': 'More bad',
    'WORST': 'Most bad',
    'WORTH': 'Value',
    'WOULD': 'Past tense of will',
    'WRITE': 'To form letters',
    'WRONG': 'Incorrect',
    'WROTE': 'Past tense of write',
    'YOUNG': 'Not old',
    'YOUTH': 'Young person'
};

// Get today's word based on date
function getTodaysWord() {
    const today = new Date();
    const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
    return DAILY_WORDS[dayOfYear % DAILY_WORDS.length];
}

// Check if a word is valid for guessing
function isValidWord(word) {
    return VALID_WORDS.includes(word.toUpperCase());
}

// Get hint for a word
function getWordHint(word) {
    return WORD_HINTS[word.toUpperCase()] || 'A valid English word';
}