define({
  "765": { "main": "/games/wow/main.js" },
  "5426": { "main": "/games/lol/main.js" }, 
  "22848": { "main": "/games/lol/main.js" }, 
  "5855": { "main": "/games/starcraft2/main.js" },
  "6350": { "main": "/games/ffxiv/main.js" },
  "7212": { "main": "/games/path_of_exile/main.js" },
  "24886": { "main": "/games/path_of_exile_2/main.js" },
  "7314": { "main": "/games/dota/main.js" },
  "7784": { "main": "/games/native_sdk/main.js" },
  "8032": { "main": "/games/minecraft/main.js" },
  "8134": { "main": "/games/native_sdk/main.js" },
  "8954": { "main": "/games/warframe/main.js" },
  "9898": { "main": "/games/hearthstone/main.js" },
  "10624": { "main": "/games/hots/main.js" },
  "10798": { "main": "/games/rocket_league/main.js" },
  "10826": { "main": "/games/rainbowsix/main.js" },
  "10844": { "main": "/games/overwatch/main.js" },
  "10906": { "main": "/games/pubg/main.js" },
  "21214": { "main": "/games/native_sdk/main.js" },
  "21216": { "main": "/games/fortnite/main.js" },
  "21236": { "main": "/games/native_sdk/main.js" },
  "21240": { "main": "/games/pubg/main.js" },
  "21308": { "main": "/games/mtga/main.js" },
  "21404": { "main": "/games/native_sdk/main.js" },
  "21450": { "main": "/games/native_sdk/main.js" },
  "21566": { "main": "/games/apex_legends/main.js" },
  "21620": { "main": "/games/legends_of_runeterra/main.js" },
  "21634": { "main": "/games/escape_from_tarkov/main.js" },
  "21640": { "main": "/games/valorant/main.js" },
  "22904": { "main": "/games/valorant/main.js" },
  "21816": { "main": "/games/new_world/main.js" },
  "21854": { "main": "/games/halo/main.js" },
  "21876": { "main": "/games/vanguard/main.js" },
  "21848": { "main": '/games/diablo2/main.js'},
  "21864": { "main": '/games/lost_ark/main.js'},
  "22638": { "main": '/games/sotf/main.js'},
  "22092": { "main": "/games/native_sdk/main.js" }, 
  "22250": { "main": "/games/native_sdk/main.js" }, 
  "22700": { "main": '/games/diablo4/main.js'},
  "23222": { "main": '/games/starfield/main.js'},
  "22730": { "main": '/games/cs2/main.js'},
  "22088": { "main": '/games/baldurs_gate_3/main.js'},
  "22328": { "main": '/games/cod/main.js'},
  "23424": { "main": '/games/cod-mw3/main.js'},
  "21656": { "main": '/games/genshin_impact/main.js'},
  "23522": { "main": '/games/vgep/lethal_company/main.js'},
  "23478": { "main": '/games/vgep/the_finals/main.js'},
  "23944": { "main": '/games/palworld/main.js'},
  "23818": { "main": '/games/vgep/stormgate/main.js'},
  "24000": { "main": '/games/vgep/helldivers2/main.js'},
  "24110": { "main": '/games/vgep/content_warning/main.js'},
  "22804": { "main": '/games/vgep/honkai/main.js'},
  "24176": { "main": '/games/vgep/manor_lords/main.js'},
  "24218": { "main": '/games/vgep/hades2/main.js'},
  "22994": { "main": '/games/vgep/xdefiant/main.js'},
  "24300": { "main": '/games/vgep/wuthering_waves/main.js'},
  "4688":  { "main":  '/games/roblox/main.js'},
  "22174": { "main":  '/games/roblox/main.js'},
  "22584": { "main": '/games/dark/main.js'},
  "24360": { "main": '/games/vgep/the_first_descendant/main.js'},
  "23930": { "main": '/games/vgep/once_human/main.js'},
  "24504": { "main": '/games/vgep/wukong/main.js'},
  "24484": { "main": '/games/spectre/main.js'},
  "24548": { "main": '/games/vgep/warhammer/main.js'},
  "24482": { "main": '/games/deadlock/main.js'},
  "24542": { "main": '/games/vgep/cod_bo6/main.js'},
  "24346": { "main": '/games/supervive/main.js'},
  "24890": { "main": '/games/marvel_rivals/main.js'},
  "22894": { "main": '/games/vgep/street_fighter6/main.js'},
  "25446": { "main": '/games/vgep/monster_hunter_wilds/main.js'},
  "25448": { "main": '/games/vgep/repo/main.js'},
  "25610": { "main": '/games/schedule1/main.js'},
  "25884": { "main": '/games/splitgate_2/main.js'},
  "25918": { "main": '/games/vgep/eldenring_nightreign/main.js'},
  "26120": { "main": '/games/rematch/main.js'},
  "26092": { "main": '/games/peak/main.js'},
});
