define({
  phasing: 15,
  data: {
    7314: {
      keys: {
        game_mode: {
          lobby_type: ["DOTA_lobby_type_name_ranked", "DOTA_lobby_type_name_custom_lobby"],
          game_mode: ["GameMode_AllDraft", "NONE", "GameMode_AllPick", "GameMode_Turbo"],
        },
        game_state_changed: {
          game_state: ["playing", "spectating"],
          match_state: ["DOTA_GAMERULES_STATE_TEAM_SHOWCASE", "DOTA_GAMERULES_STATE_INIT"],
          player_team: ["radiant", "dire"],
        },
        team_score: {
          radiant: [2],
          dire: [2],
        },
        party: {
          isLeader: ["true", "false"],
          isCoach: ["true", "false"],
        },
        new_game: ["1"],
        game_over: ["1"],
        players: {
          role: [0, 1],
          team: [0, 1, 2],
        },
      },
      enable: true,
      description: "Dota match state data",
    },
    10826: {
      keys: {
        phase: ["lobby", "teammates", "announce", "operator_select", "loading", "round_results"],
        map_id: ["HOUSE", "UNKNOWN"],
        round_outcome_type: ["team_has_been_eliminated", "bomb_detonated", "bomb_deactivated", "objective_secured", "objective_protected", "time_has_expired", "extracted_thehostages", "killed_hostages"],
        roster_0: {
          team: ["Blue"],
          kills: [1],
          deaths: [1],
          operator: ["ROCK", "UNKNOWN"],
        },
      },
      enable: true,
      description: "R6 data",
    },
    10906: {
      keys: {
        phase: ["lobby", "aircraft", "loading_screen", "airfield", "freefly", "landed"],
        mode: ["solo", "duo", "squad"],
        bodyPosition: ["leanLeft", "leanRight", "straight"],
        inVehicle: [true, false],
        aiming: ["null", "focusedAim", "aimDownSight", "aimDownSight_holding_breath"],
        view: ["TPP", "FPP"],
        movement: ["normal", "fast", "stealth"],
        map: ["Baltic_Main", "DihorOtok_Main"],
        kill: ["1"],
        death: ["1"],
        knockout: ["1"],
        knockedout: ["1"],
        headshot: ["1"],
        revived: ["1"],
      },
      enable: true,
      description: "PUBG data",
    },
    21216: {
      keys: {
        phase: ["lobby", "aircraft", "loading_screen", "airfield", "freefly", "replay"],
        kills: ["5"],
        mode: ["solo", "duo", "squad", "Playlist_Respawn", "Playlist_Campaign", "Playlist_PlaygroundV2", "Playlist_Creative_PlayOnly", "Playlist_ShowdownAlt_Solo", "Playlist_ShowdownAlt_Squads", "Playlist_Crucible_Solo", "Playlist_BattleLab", "Playlist_Creative_ZebraWallet_Random", "Playlist_Creative_ZebraWallet_Random2", "Playlist_NoBuildBR_Solo", "Playlist_NoBuildBR_Duo", "Playlist_NoBuildBR_Trio", "Playlist_NoBuildBR_Squad"],
        rank: ["1", "14", "10", "40"],
        total_teams: ["30"],
        total_players: ["50"],
        health: ["80"],
        accuracy: ["0.500000"],
        shield: ["40"],
        over_shield: ["50"],
        total_shots: ["50"],
        selected_slot: {
          isPrimary: [true],
          slot: ["1"],
        },
        selected_material: ["2"],
        kill: ['1'],
        death: ["1"],
        revived: ['1'],
        matchStart: ["1"],
        matchEnd: ["1"],
        title_mnemonic: ["playlist_nobuildbr_solo"],
        game_title: ["Solo"],
        game_type: ["Battle Royal"],
        privacy: ["public"],
        server: ["EU"],
        vbucks: ["300"],
        in_vehicle: [true],
        emote_start: ['1'],
      },
      enable: true,
      description: "Fortnite data",
    },
    21566: {
      keys: {
        game_mode: ["#PL_FIRINGRANGE", "#PL_TRAINING", "#PL_DUO", "#PL_TRIO", "#PL_Ranked_Leagues", "#SHADOWROYALE_MODE"],
        mode_name: ["Duo", "UNKNOWN"],
        map_name: ["Olympus", "UNKNOWN"],
        ultimate_cooldown: {
          ultimate_cooldown: ["10"],
        },
        match_state: ["active", "inactive"],
        team_info: {
          team_state: ["active", "eliminated"],
        },
        victory: [true, false],
        match_summary: {
          rank: ["10"],
          teams: ["20", "25"],
          squadKills: ["2"],
        },
        tabs: {
          kills: [2],
          assists: [2],
          teams: [15],
          players: [10],
          damage: [100],
          cash: [150],
        },
        kill_feed: {
          action: ["Bleed_out"],
          weaponName: ["r301"],
        },
        totalDamageDealt: ["100"],
        phase: ["combat", "freefly"],
        map_id: null,
        healed_from_ko: ["1"],
        respawn: ["1"],
        arena_score: {
          my_team: [2],
          enemy_team: [2],
        },
      },
      enable: true,
      description: "Apex data",
    },
    21640: {
      keys: {
        game_mode: {
          mode: ["bomb", "deathmatch", "quick_bomb", "range", "escalation", "npe", "replication"],
          ranked: null
        },
        region: ["esp", "isr"],
        agent: ["Clay_PC_C", "Pandemic_PC_C", "Wraith_PC_C", "Hunter_PC_C", "Thorne_PC_C", "Phoenix_PC_C", "Wushu_PC_C", "Gumshoe_PC_C", "Sarge_PC_C", "Breach_PC_C", "Vampire_PC_C", "Killjoy_PC_C", "Guide_PC_C", "Stealth_PC_C", "Rift_PC_C", "Grenadier_PC_C", "Deadeye_PC_C", "Sprinter_PC_C"],
        round_number: ["1", "2", "3"],
        round_phase: ["shopping", "combat", "end", "game_end"],
        team: ["attack", "defense"],
        match_outcome: ["victory", "draw", "defeat"],
        scene: ["MainMenu", "Triad", "Duality", "Bonsai", "Ascent", "Port", "Foxtrot", "Canyon", "Range", "CharacterSelectPersistentLevel"],
        state: ["WaitingToStart", "LeavingMap", "Aborted", "InProgress", "Init", "WaitingPostMatch"],
        map: ["Foxtrot", "Pitt", "Duality"],
        kill: ["6"],
        death: ["6"],
        roster_2: {
          name: ["Jett"],
          character: ["Wushu"],
          rank: [11, 0],
          locked: [true, false],
          teammate: [true, false],
          local: [true, false],
        },
        scoreboard_2: {
          character: ["Wushu"],
          kills: [20],
          deaths: [15],
          assists: [10],
          money: [4000],
          alive: [true],
          shield: [2, 4],
          ult_points: [5],
          ult_max: [7],
          weapon: ["TX_Hud_Sniper_Operater"]
        },
        kill_feed: {
          weapon: ["TX_Hud_LMG"],
          ult: ["TX_Thorne_Heal"],
          headshot: [true],
        },
        match_score: {
          team_0: [2],
          team_1: [2],
        },
        is_pbe: [true],
        planted_location: ["B"],
      },
      enable: true,
      description: "Valorant data",
    },
    22904: {
      keys: {
        game_mode: {
          mode: ["bomb", "deathmatch", "quick_bomb", "range", "escalation", "npe", "replication"],
          ranked: null
        },
        region: ["esp", "isr"],
        agent: ["Clay_PC_C", "Pandemic_PC_C", "Wraith_PC_C", "Hunter_PC_C", "Thorne_PC_C", "Phoenix_PC_C", "Wushu_PC_C", "Gumshoe_PC_C", "Sarge_PC_C", "Breach_PC_C", "Vampire_PC_C", "Killjoy_PC_C", "Guide_PC_C", "Stealth_PC_C", "Rift_PC_C", "Grenadier_PC_C", "Deadeye_PC_C", "Sprinter_PC_C"],
        round_number: ["1", "2", "3"],
        round_phase: ["shopping", "combat", "end", "game_end"],
        team: ["attack", "defense"],
        match_outcome: ["victory", "draw", "defeat"],
        scene: ["MainMenu", "Triad", "Duality", "Bonsai", "Ascent", "Port", "Foxtrot", "Canyon", "Range", "CharacterSelectPersistentLevel"],
        state: ["WaitingToStart", "LeavingMap", "Aborted", "InProgress", "Init", "WaitingPostMatch"],
        map: ["Foxtrot", "Pitt", "Duality"],
        kill: ["6"],
        death: ["6"],
        roster_2: {
          name: ["Jett"],
          character: ["Wushu"],
          rank: [11, 0],
          locked: [true, false],
          teammate: [true, false],
          local: [true, false],
        },
        scoreboard_2: {
          character: ["Wushu"],
          kills: [20],
          deaths: [15],
          assists: [10],
          money: [4000],
          alive: [true],
          shield: [2],
          ult_points: [5],
          ult_max: [7],
          weapon: ["TX_Hud_Sniper_Operater"]
        },
        kill_feed: {
          weapon: ["TX_Hud_LMG"],
          ult: ["TX_Thorne_Heal"],
          headshot: [true],
        },
        is_pbe: [true],
      },
      enable: true,
      description: "Valorant PBE data",
    },
    21854: {
      keys: {
        scene: ["ingame"],
        playlist: null,
        game_type: null,
        match_outcome: ["victory", "defeat", "tie"],
      },
      enable: true,
      description: "Halo data",
    },
    21634: {
      keys: {
        map: ["Woods", "Town", "laboratory", "arkov Streets", "Suburbs", "Interchange", "Lighthouse"],
        phase: ["scene_Login", "scene_TimeHasCome"],
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
        raid_type: ["scav"],
        session_type: ["PVP"],
        quests_list: {
          quest_status: ["AvailableForStart"],
          location: ["Ground Zero"],
          quest_type: ["PickUp"],
        },
      },
      enable: true,
      description: "Tarkov data",
    },
    5426: {
      keys: {
        game_mode: ["lol"],
        match_clock: ["10"],
        usedAbility: {
          type: ["4"]
        },
        abilityReady: {
          type: ["4"]
        },
        jungle_camp_2: {
          name: ["monsterCamp_2"],
          alive: [true, false],
          icon_status: ["0"],
        },
        announcer: {
          name: ["turret_destroy"],
        },
        team_frames_1: {
          ult_cd: [47],
        },
        respawn: ["1"],
      },
      enable: true,
      description: "LOL data",
    },
    22848: {
      keys: {
        game_mode: ["lol"],
        match_clock: ["10"],
        usedAbility: {
          type: ["4"]
        },
        jungle_camp_2: {
          name: ["monsterCamp_2"],
          alive: [true, false],
          icon_status: ["0"],
        },
        announcer: {
          name: ["turret_destroy"],
        },
        team_frames_1: {
          ult_cd: [47],
        },
        respawn: ["1"],
      },
      enable: true,
      description: "LOL PBE data",
    },
    21556: {
      keys: {
        is_pbe: [true, false],
        game_mode: ["ARENA"],
        match_clock: ["10"],
        round_start: ["1", "2"],
        round_end: ["1"],
        respawn: ["1"],
        round_number: ["1"],
        match_outcome: ["victory", "defeat"],
        round_outcome: ["victory", "defeat"],
        level: ["1"],
        match_started: [true, false],
        match_start: ["1"],
        battle_start: ["1"],
        battle_end: ["1"],
        total_heal: ["250"]
      },
      enable: true,
      description: "LOL Arena data",
    },
    215561: {
      keys: {
        is_pbe: [true, false],
        game_mode: ["arena"],
        match_clock: ["10"],
        round_start: ["1", "2"],
        round_end: ["1"],
        respawn: ["1"],
        round_number: ["1"],
        match_outcome: ["victory", "defeat"],
        round_outcome: ["victory", "defeat"],
        level: ["1"],
        match_started: [true, false],
        match_start: ["1"],
        battle_start: ["1"],
        battle_end: ["1"],
        total_heal: ["250"]
      },
      enable: true,
      description: "LOL Arena PBE data",
    },
    13956: {
      keys: {
        is_pbe: [true, false],
        game_mode: ["SWARM"],
        match_started: [true, false],
        match_start: ["1"],
        minionKills: ["10", "20"],
        death: ["1"],
        deaths: ["1"],
      },
      enable: true,
      description: "LOL Swarm data",
    },
    21568: {
      keys: {
        is_pbe: [true, false],
        game_mode: ["BRAWL"],
        match_started: [true, false],
        match_start: ["1"],
        minionKills: ["10", "20"],
        death: ["1"],
        deaths: ["1"],
      },
      enable: true,
      description: "LOL BRAWL data",
    },
    7212: {
      keys: {
        character_level: ["2"],
        current_zone: ["The City of Sarn", "Lioneye's Watch", "The Twilight Strand"],
        opened_page: ["inventory", "passive_tree", "character_sheet", "stash", "map_device", "pantheon", "crafting_bench"],
        boss_kill: null,
        chat: ["You have entered Lioneye's Watch."],
        chat_language: ["en"],
      },
      enable: true,
      description: "POE data",
    },
    24886: {
      keys: {
        character_level: ["2"],
        current_zone: ["The City of Sarn", "Lioneye's Watch", "The Twilight Strand"],
        opened_page: ["inventory", "passive_tree", "character_sheet", "stash", "map_device", "pantheon", "crafting_bench"],
        boss_kill: null,
        chat: ["You have entered Lioneye's Watch."],
        chat_language: ["en"],
        in_town: [true],
        match_start: ["1"],
        match_end: ["1"],
        scene: ["login", "select_character", "loading", "in_game"],
      },
      enable: true,
      description: "POE 2 data",
    },
    10798: {
      keys: {
        action_points: ["Shot On Goal", "Goal", "First Touch", "Center Ball", "Pool Shot", "Assist", "Clear Goal", "Demolish", "Save", "Epic Save"],
        started: [true],
        ended: [true],
        matchType: ["Lobby", "Private", "Online", "Offline"],
        maxPlayers: ["0", "2", "4", "6"],
        gameMode: ["Soccar", "Breakout", "Basketball", "Hockey", "Items", "Unknown"],
        gameState: ["WaitingForPlayers", "Countdown", "Active", "PostGoalScored", "ReplayPlayback", "PrePodiumSpotlight", "Finished", "Unknown", "PodiumSpotlight"],
        arena: ["Random", "None"],
        goals: ["0", "2", "4"],
        score: ["100", "200"],
        team_score: ["2"],
        trade_menu_opened: ["true", "false"],
      },
      enable: true,
      description: "Rocket league data",
    },
    21848: {
      keys: {
        player_level: ["2", "4", "6", "8"],
        player_class: ["PALADIN"],
        player_experience: ["1100", "1200", "1500", "2000"],
        act: ["1", "2", "3", "4"],
        item_5: {
          inv_page: null,
          body_loc: null,
        },
      },
      enable: true,
      description: "Diablo 2 data",
    },
    21570: {
      keys: {
        is_pbe: [true, false],
        game_mode: ["TFT"],
        xp: {
          level: [5, 6],
        },
        health: ["10", "20"],
        rank: ["8"],
        gold: ["8"],
        battle_state: {
          in_progress: [true],
        },
        match_state: {
          in_progress: [true],
        },
        round_type: {
          stage: ["4-1"],
          name: ["Carousel", "PVE", "PVP"],
          type: ["PVE"],
        },
        battle_start: ["PVP"],
        round_start: ["PVP"],
        picked_augment: ["TFT14_Augment_SylasCarry_combo", "TFT8_Augment_AnnieSupport", "TFT6_Augment_SecondWind2", "TFT7_Augment_AxiomArc2", "TFT6_Augment_CelestialBlessing2", "TFT7_Augment_ScopedWeapons1", "TFT6_Augment_Distancing2", "TFT8_Augment_SivirSupport"],
        picked_item: ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_RecurveBow", "TFT_Item_NegatronCloak", "TFT_Item_BFSword"]
      },
      enable: true,
      description: "TFT data",
    },
    21864: {
      keys: {
        player_class: ["DESTROYER", "BARD"],
        mob_details: {
          grade: ["BOSS", "EPIC_RAID"],
        },
        kill: {
          grade: ["BOSS"],
          name: null,
        },
      },
      enable: true,
      description: "Lost Ark data",
    },
    8032: {
      keys: {
        match_start: ["1"],
        dimension: ["minecraft:overworld"],
        biome: ["minecraft:forest"],
        scene_key: ["gui.stats"],
        server_info: {
          reference: ["0", "1"],
        },
      },
      enable: true,
      description: "Minecraft data",
    },
    21308: {
      keys: {
        draft_start: ["1"],
        draft_end: ["1"],
      },
      enable: true,
      description: "MTGA data",
    },
    22638: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
      },
      enable: true,
      description: "SOTF data",
    },
    765: {
      keys: {
        addon_0: {
          status: [1],
        },
      },
      enable: true,
      description: "WOW data",
    },
    22700: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
      },
      enable: true,
      description: "Diablo 4 data",
    },
    10844: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        round_start: ["1"],
        round_end: ["1"],
        elimination: ["1"],
        death: ["1"],
        respawn: ["1"],
        revive: ["1"],
        assist: ["1"],
        map: ["1694"],
        game_mode: ["23"],
        game_state: ["match_in_progress"],
        game_type: ["UNKNOWN", "UNRANKED", "CUSTOM_GAME", "PRACTICE", "ARCADE", "TUTORIAL", "SKIRMISH", "VS_AI", "DEATHMATCH", "RANKED", "HERO_MASTERY"],
        match_outcome: ["victory", "defeat"],
        game_queue_type: ["ROLE_QUEUE", "OPEN_QUEUE", "UNKNOWN", "unknown"],
        party_player_count: ["1", "2"],
        kill_feed: {
          is_attacker_teammate: [true],
          is_supporter_teammate: [true],
        },
      },
      enable: true,
      description: "Overwatch 2 data",
    },
    23222: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
      },
      enable: true,
      description: "Starfield data",
    },
    22088: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
      },
      enable: true,
      description: "Baldur's Gate III data",
    },
    22328: {
      keys: {
        match_start: ["1"],
        match_end: ["victory", "defeat"],
        scene: ["lobby_mw2", "lobby_wz2", "in_game", "airplane"],
        mode: ["mw2", "warzone"]
      },
      enable: true,
      description: "COD MW2 + WZ2 data",
    },
    23424: {
      keys: {
        match_start: ["1"],
        match_end: ["victory", "defeat"],
        scene: ["lobby_mw3", "in_game"],
        mode: ["mw3"]
      },
      enable: true,
      description: "COD MW3 data",
    },
    21656: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
      },
      enable: true,
      description: "Genshin Impact data",
    },
    23522: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
        respawn: ["1"],
        scene: null,
      },
      enable: true,
      description: "Lethal Company data",
    },
    23944: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
        respawn: ["1"],
        knockout: ["1"],
        revive: ["1"],
        scene: null,
      },
      enable: true,
      description: "Palworld data",
    },
    23478: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
        respawn: ["1"],
        scene: null,
        elimination: [5],
      },
      enable: true,
      description: "The Finals data",
    },
    23818: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
      },
      enable: true,
      description: "Stormgate data",
    },
    22730: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        round_start: ["1"],
        death: ["2"],
        kill: ["2"],
        match_outcome: ["win"],
        score: {
          team_t: [2],
        },
        kill_feed: {
          weapon: ["m4a1_silencer"],
          headshot: [true],
        },
        roster_1: {
          team: ["T"],
          score: [1],
          mvps: [1],
          assists: [1]
        },
        mm_state: ["searching", "canceled", "connect", "unavailable"],
      },
      enable: true,
      description: "Counter Strike 2 data",
    },
    24000: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
        scene: null,
      },
      enable: true,
      description: "Helldivers 2 data",
    },
    24110: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
      },
      enable: true,
      description: "Content Warning data",
    },
    22804: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        battle_start: ["1"],
        battle_end: ["1"],
        match_outcome: ["victory", "defeat"],
        scene: null,
      },
      enable: true,
      description: "Honkai data",
    },
    24176: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
      },
      enable: true,
      description: "Manor Lords data",
    },
    24218: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["1"]
      },
      enable: true,
      description: "Hades 2 data",
    },
    22994: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["1"],
        match_outcome: ["victory", "defeat"],
        elimination: [5],
      },
      enable: true,
      description: "Xdefiant data",
    },
    24300: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["1"],
        reapawn: ["1"],
      },
      enable: true,
      description: "Wuthering Waves data",
    },
    4688: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        record_start: ["1"],
        record_end: ["1"],
      },
      enable: true,
      description: "Roblox data",
    },
    22584: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        kill: ["1"],
        death: ["1"],
        match_outcome: ["victory", "defeat"],
      },
      enable: true,
      description: "Dark and Darker data",
    },
    24484: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        kill: ["1"],
        death: ["1"],
        assist: ["1"],
      },
      enable: true,
      description: "Spectre Divide data",
    },
    24360: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
      },
      enable: true,
      description: "The First Descendant data",
    },
    23930: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        knockout: ["1"],
        level_up: ["1"],
        death: ["1"],
      },
      enable: true,
      description: "Once Human data",
    },
    24504: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["killed_by_boss"],
        kill: ["boss_kill"]
      },
      enable: true,
      description: "Wukong data",
    },
    24548: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["1"],
        knmockout: ["1"]
      },
      enable: true,
      description: "Warhammer data",
    },
    24482: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        game_mode: {
          match_mode: ["Unranked"],
          game_mode: ["Normal"],
        },
        phase: ["Init", "GameInProgress"],
        team_score: {
          sapphire: ["5"],
          amber: ["5"],
        },
        kill: ["1"],
        death: ["1"],
        assist: ["1"],
      },
      enable: true,
      description: "Deadlock data",
    },
    21816: {
      keys: {
        map: null,
      },
      enable: true,
      description: "New world data",
    },
    24542: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        game_mode: ["black_ops_6", "warzone"],
      },
      enable: true,
      description: "COD BO6 data",
    },
    24346: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["1"],
        kill: ["1"],
        assist: ["1"],
      },
      enable: true,
      description: "Supervive data",
    },
    24890: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["1"],
        kill: ["1"],
        assist: ["1"],
        player_stats: {
          damage_dealt: [40, 80],
          damage_block: [40, 80],
        },
        game_type: ["Competitive"],
        game_mode: ["Convergence"],
        map: ["Shin-shibuya", "UNKNOWN"],
        roster_0: {
          character_name: ["UNKNOWN"],
          kills: [8],
          deaths: [8],
          assists: [8],
          accuracy: [50],
          elo_score: [3000],
        },
        banned_characters: {
          character_name: ["THE THING"],
          is_teammate: [false],
        },
        objective_progress: {
          game_mode: ["Convoy"],
          checkpoint: [2],
          left_capture: [80],
          right_capture: [80],
          team: ["Defense"],
        },
        ability_cooldown_1: [10],
      },
      enable: true,
      description: "Marvel Rivals data",
    },
    22894: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        round_start: ["1"],
        round_end: ["1"],
        scene: ["ingame"],
        game_mode: ["fighting_ground", "battle_hub"],
        match_outcome: ["victory"],
      },
      enable: true,
      description: "Street Fighter 6 data",
    },
    25446: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        boss_kill: ["1"],
        quest_start: ["quest_start"],
        quest_failed: ["quest_failed"],
        quest_complete: ["quest_complete"],
        scene: ["ingame"],
        death: ["death"],
      },
      enable: true,
      description: "Monster Hunter Wilds data",
    },
    25448: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        round_start: ["1"],
        round_end: ["1"],
        scene: ["ingame"],
        death: ["death"],
      },
      enable: true,
      description: "R.E.P.O data",
    },
    25610: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        sleep_start: ["1"],
        sleep_end: ["1"],
        pursuit_level: ["arrested"],
      },
      enable: true,
      description: "Schedule 1 data",
    },
    25884: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        round_start: ["1"],
        round_end: ["1"],
        scene: null,
        death: ["1"],
        kill: ["1"],
      },
      enable: true,
      description: "Splitgate 2 data",
    },
    25918: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        scene: null,
        death: ["death"],
        kill: ["boss_kill"]
      },
      enable: true,
      description: "Elden Ring Nightreign data",
    },
    26120: {
      keys: {
        match_start: ["1"],
        match_end: ["1"],
        goal: ["1"],
        match_outcome: ["victory", "defeat"],
        scene: null,
        game_type: ["QuickMatch3v3"],
      },
      enable: true,
      description: "Rematch data",
    },
    26092: {
      keys: {
        scene: null,
        match_start: ["1"],
        match_end: ["1"],
        death: ["1"],
        checkpoint: ["1"],
        game_mode: ["offline", "host"]
      },
      enable: true,
      description: "Peak data",
    },
  },
});


