// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.launcherProcess.enabled", true);
user_pref("idle.lastDailyNotification", 1752443382);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("toolkit.startup.last_success", 1754067044);
