define([], function () {
  const Constants = {
    Game_Modes: {
      "#PL_FIRINGRANGE": "Firing Range",
      "#PL_TRAINING": "Training",
      "#PL_DUO": "Duo",
      "#PL_TRIO": "Trio",
      "#PL_Ranked_Leagues": "Ranked",
      "#GAMEMODE_ARENAS": "Arenas",
      "#GAMEMODE_ARENAS_RANKED": "Ranked Arenas",
      "#SHADOWROYALE_MODE": "Shadow Royale",
      "#SURVIVAL_HARDCORE": "Hardcore Royale",
      "#PL_DUO_DATE": "Duo",
      "#TDM_NAME": "Team Deathmatch",
      "#GAME_MODE_GUNGAME": "Gun Run",
      "#CONTROL_NAME": "Control",
      "#SURVIVAL_HEATWAVE": "Heatwave",
      "#PL_TOURNAMENT_DESERTLANDS_MU4": "Tournament",
      "#PL_TOURNAMENT_TROPIC_MU1": "Tournament",
      "#PL_TOURNAMENT_CANYONLANDS_HU": "Tournament",
      "#PL_TOURNAMENT_OLYMPUS_MU2": "Tournament",
      "#PL_TOURNAMENT_MOON_BASE": "Tournament",
      "#PL_TOURNAMENT_TROPIC_MU2": "Tournament",
      "#PL_TOURNAMENT_TROPIC_NORING": "Tournament",
      "#PL_TOURNAMENT_MOON_NORING": "Tournament",
      "#PL_TOURNAMENT_DESERTLANDS_HU": "Tournament",
      "#PL_TOURNAMENT_DESERTLANDS_NORING": "Tournament",
      "#GAME_MODE_SWAT": "Deadeye",
      "#SHOTGUNS_AND_SNIPERS": "Armed and Dangerous",
      "#PL_TRIO_HALLOWEEN_18_1_Harbinger_NAME": "Living Shell Trio",
      "#PL_TRIO_HALLOWEEN_18_1_NAME": "Tricks N Treats Trios",
      "#STRIKEOUT_TITLE": "Three Strikes",
      "#SHADOW_ARMY_NAME": "Revenant Uprising",
      "#GOLDEN_HORSE_LTM_TITLE": "Final Fantasy Takeover",
      "#BATTLE_RUSH_TITLE": "Straight Shot",
      "#FREEDM_LOCKDOWN_MODE": "Lockdown",
      "#SURVIVAL_MODE_SOLOS": "Solos",
      "#PL_QUAD": "Quads",
      "#BTDM_NAME": "Big Deathmatch",
      "#BOTPLAYGROUND_BOT_ROYALE_HEADER": "BOT Royale",
      "#PL_FREERESPAWNS": "Trios Revival",
      "#GAMEMODE_OBJECTIVE_BR": "Knockout",
      "#PL_TRIO_HALLOWEEN_22_1_NAME": "Trio",
      "#HALLOWEEN_22_1_TDM": "Team Deathmatch",
      "#HALLOWEEN_22_1_LOCKDOWN": "Lockdown",
      "#HALLOWEEN_22_1_CONTROL": "Control",
      "#PL_DAYZERO": "Launch Royale",
      "#RANKED_TITLE": "Ranked",
    },


    Map_Names: {
      "mp_rr_canyonlands_hu": "King Canyon",
      "mp_rr_canyonlands_staging": "King Canyon",
      "mp_rr_freedm_skulltown": "Kings Canyon",
      "mp_rr_tropic_island_mu1": "Storm Point",
      "mp_rr_desertlands_mu3": "World's Edge",
      "mp_rr_olympus_mu2": "Olympus",
      "mp_rr_divided_moon": "Broken Moon",
      "mp_rr_divided_moon_mu1": "Broken Moon",
      "mp_rr_arena_habitat": "Habitat 4",
      "mp_rr_aqueduct": "Overflow",
      "mp_rr_party_crasher": "Party Crasher",
      "mp_rr_arena_phase_runner": "Phase Runner",
      "mp_rr_arena_composite": "Drop off",
      "mp_rr_desertlands_mu4": "World's Edge",
      "mp_rr_arena_skygarden": "Encore",
      "mp_rr_desertlands_hu": "World's Edge",
      "mp_rr_canyonlands_staging_mu1": "King Canyon",
      "mp_rr_tropic_island_mu1_storm": "Storm Point",
      "mp_rr_desertlands_night": "World's Edge",
      "mp_rr_olympus_mu1_night": "Olympus",
      "mp_rr_canyonlands_mu1_night": "Kings Canyon",
      "mp_rr_tropic_island_mu2": "Storm Point",
      "mp_rr_thunderdome": "Thunderdome",
      "mp_rr_district": "E-District",
      "mp_rr_district_halloween": "E-District",
      "mp_rr_tropic_island_mu2_landscape": "Storm Point",
      "mp_lobby": "Lobby"
    }

  };

  return Constants;
});