define({
  "mp_weapon_energy_ar": "HAVOC",
  "mp_weapon_hemlok": "Hemlok Burst AR",
  "mp_weapon_vinson": "VK-47 Flatline",
  "mp_weapon_rspn101": "R-301 Carbine",
  "mp_weapon_lstar": "L-Star",
  "mp_weapon_esaw": "Devotion",
  "mp_weapon_lmg": "M600 Spitfire",
  "mp_weapon_wingman": "Wingman",
  "mp_weapon_autopistol": "RE-45 Auto",
  "mp_weapon_semipistol": "P2020",
  "mp_weapon_shotgun": "EVA-8 Auto",
  "mp_weapon_energy_shotgun": "Peacekeeper",
  "mp_weapon_shotgun_pistol": "Mozambique Shotgun",
  "mp_weapon_mastiff": "Mastiff Shotgun",
  "mp_weapon_pdw": "Prowler Burst PDW",
  "mp_weapon_r97": "R-99",
  "mp_weapon_alternator_smg": "Alternator SMG",
  "mp_weapon_volt_smg": "Volt SMG",
  "mp_weapon_doubletake": "Triple Take",
  "mp_weapon_dmr": "Longbow DMR",
  "mp_weapon_g2": "G7 Scout",
  "mp_weapon_sentinel": "Sentinel",
  "mp_weapon_defender": "Charge Rifle",
  "mp_weapon_sniper": "Kraber .50-cal Sniper",
  "mp_weapon_thermite_grenade": "Thermite Grenade",
  "mp_weapon_frag_grenade": "Frag Grenade",
  "mp_weapon_grenade_emp": "Arc Star",
  "mp_weapon_deployable_medic": "Health Drone",
  "mp_ability_care_package": "Care Package",
  "mp_weapon_bubble_bunker": "Dome of Protection",
  "mp_weapon_grenade_defensive_bombardment": "Defensive Bombardment",
  "mp_ability_grapple": "Grappling Hook",
  "mp_weapon_zipline": "Zipline Gun",
  "mp_weapon_jump_pad": "Launch Pad",
  "mp_ability_phase_walk": "Into the Void",
  "mp_weapon_phase_tunnel": "Dimensional Rift",
  "mp_weapon_grenade_bangalore": "Smoke Launcher",
  "mp_weapon_grenade_creeping_bombardment": "Rolling Thunder",
  "mp_weapon_dirty_bomb": "Nox Gas Trap",
  "mp_weapon_grenade_gas": "Nox Gas Grenade",
  "mp_weapon_melee_survival": "Melee",
  "mp_weapon_wraith_kunai_primary": "Kunai Melee", 
  "mp_ability_consumable": "Health/Shield",
  "mp_weapon_incap_shield": "Knockdown Shield",
  "melee_pilot_emptyhanded": "Empty Handed",
  "mp_weapon_dragon_lmg": "Rampage LMG",
  "mp_weapon_bow": "Bocek Compound Bow",
  "mp_weapon_3030": "30-30 Repeater",
  "mp_weapon_car": "C.A.R. SMG",
  "mp_weapon_nemesis": "Nemesis",
  "mp_weapon_wingman_crate": "Wingman",
  "mp_weapon_pdw_crate": "Prowler Burst PDW"
})