define([], function () {
    const Constants = {
        hero_id: {
            0: "UNKNOWN",
            2: "REAPER",
            3: "TRACER",
            4: "MERCY",
            5: "HANZO",
            6: "TORBJORN",
            7: "REINHARDT",
            8: "PHARAH",
            9: "WINSTON",
            10: "WIDOWMAKER",
            21: "BASTION",
            22: "SYMMETRA",
            32: "ZENYATTA",
            41: "GENJI",
            64: "ROADHOG",
            66: "CASSIDY",
            101: "JUNKRAT",
            104: "ZARYA",
            110: "SOLDIER76",
            121: "LUCIO",
            122: "DVA",
            221: "MEI",
            302: "SOMBRA",
            303: "DOOMFIST",
            315: "ANA",
            318: "ORISA",
            405: "BRIGITTE",
            418: "MOIRA",
            458: "WRECKINGBALL",
            492: "SOJOURN",
            512: "ASHE",
            518: "ECHO",
            545: "BAPTISTE",
            561: "KIRIKO",
            566: "JUNKERQUEEN",
            571: "SIGMA",
            653: "RAMATTRA",
            657: "LIFEWEAVER",
            778: "MAUGA",
            796: "ILLARI",
            810: "FREJA",
            811: "VENTURE",
            869: "JUNO",
            866: "HAZARD"
        },
        hero_role: {
            0: "UNKNOWN",
            1: "TANK",
            2: "DAMAGE",
            3: "SUPPORT",
        },
        game_type: {
            0: "UNKNOWN",
            1: "UNRANKED",
            2: "CUSTOM_GAME",
            3: "PRACTICE",
            4: "ARCADE",
            5: "TUTORIAL",
            6: "SKIRMISH",
            7: "VS_AI",
            8: "DEATHMATCH",
            9: "RANKED",
            10: "HERO_MASTERY",
            11: "HERO_MASTERY_SOLO",
            16: "STADIUM",

        },
        game_queue_type: {
            0: "UNKNOWN",
            1: "ROLE_QUEUE",
            2: "OPEN_QUEUE",
        },
        roster_delay: { 
            "23": 30000,
            "224": 30000,
            "109": 30000,
            "21": 45000,
            "22": 45000,
            "90": 0 
        },
    };

    return Constants;
});